### ISSUE TITLE
bridges | Implement basic animal Inventory

### ISSUE THREAD

**Issue by mango-gremlin** [mango-gremlin/arch-enemies#172]
## Motivation
Way to track which animals you have in your party/and can use for bridges.

## Implementation
The implementation should provide a basic inventory:

This inventory should be like the inventory already implemented in the overworld.

It should have the following functionality
- saves how many of each animal you have (should be expandable to work with the singleton in the future -> so that it can take the inventory content information from the player in the future)
  The amounts of each animal should/could be saved in a dictionary where key = AnimalType (as represented in the singleton) and value = how many you have 
  It would be great if each value, before it is saved into the dict, is exported with @export to that you can edit the animal amounts in the godot inspector.
- save how many animals have been used so far
- display and disable placement if animal not available
- the inventory should only take info out of the singleton, *not edit it* unless the level is completed and the player goes back to the overworld.

There should be a basic UI as follows:
- hbox container that contains buttons for each animal type & shows how many you have of each type
- the buttons should spawn the respective animal
- spawning animal should update inventory

**Comment by ScatteredDrifter** [comment]
I have some comments regarding the inventory system. 

Because we are tracking the inventory system globally _constantly_ it makes way more sense to update and query from there instead of creating an instance in each bridge game ( which would then be populated by the global state I think ). 

This way you could add basic interfaces `obtain_animal_amount(AnimalType)...` or similar to interact with. 

Regarding this representation of the inventory:
>  where key = animal name and value = how many you have

Instead of "animal name" you could make use of the AnimalType which will be introduced in #134  ( currently not done yet, sorry ) 

Its **structure is similar/equal** to the ItemInventory which can be found in our main-branch already. 
So maybe if you could make use of this, that would simplify integration at some later point ^^.

I will write an entry to the wiki soon to provide further information.

**Comment by mango-gremlin** [comment]
So the idea was so update and query from the singleton which I assumed also tracked the inventory, if thats what you mean. So yes thats what we had in mind. 
So the idea was to get the inventory from the singleton/player that tracks everything, when you load a bridge level. But only update it once you leave the bridge level AND have completed it, since if you dont complete it, i assume no animals are used up and the level doesnt save until you complete it. I think this will be easier to implement than saving your bridge state as you leave, as I dont think the birdges group could complete this in time with everything else still needed.

Representing the animals with the animal type sounds like a good idea, please elaborate on this when the singleton is finished. 
But to make this implementation compatible with the singleton, how should the animalType be used, and what does @Raining-Cloud need to keep in mind?

Also making use of the already implemented inventory from the overworld is a great idea, and I will also add this to the issue description. 

Thank you for your input!
