### ISSUE TITLE
Snapping allows placement of invalid positions

### ISSUE THREAD

**Issue by marcel-iv** [mango-gremlin/arch-enemies#76]
## Description

**To Reproduce**
1. drag one snake over the drop zones of another animal
2. drop the snake, while it is still touching the drop zone, but with the dragged snake being on the outmost part of a grid square
3. snake will snap to outer grid square (outside of the drop zone), but will remain there and not snap back

**Expected behavior**
Snake snaps to outer grid square and resets to original position, as the snapped position is not valid.

**Screenshots**
https://github.com/mango-gremlin/arch-enemies/assets/104799849/6de7d2c6-f273-405a-911f-02209e5831e5

## Solution Proposal
The problem arises, because the snap to grid happens in the _process function, so the variables is_inside_dragable and is_inside_forbidden are not updated, as the dragged animal hasn't moved. Everything occurs in the same frame, so no update is possible. To fix this, maybe use signals emitted by events to handle the snap to grid, so it occurs in different frames (or rather, before _process is automatically called)

**Comment by mango-gremlin** [comment]
probably this happens because of your grid snapping, which rounds to the nearest 10's coordinate right? and if its on the rim it thinks the nearest coordinate is outside of the dropzone?
maybe we can edit the snap to grid function to include this case, which should get around the problem of the stuff happening at the same time?
